name: 'Detect Changed Components and Pipelines'
description: 'Detects changed components, pipelines, and file types (Python, Markdown, YAML) in the repository'
author: 'Kubeflow Pipelines Components Team'

inputs:
  base-ref:
    description: 'Base Git reference to compare against (e.g., main, origin/main)'
    required: false
    default: ${{ format('origin/{0}', github.event.pull_request.base.ref || github.event.repository.default_branch) }}
  head-ref:
    description: 'Head Git reference to compare (defaults to current HEAD)'
    required: false
    default: 'HEAD'
  include-third-party:
    description: 'Whether to include third_party components and pipelines'
    required: false
    default: 'true'
  filter:
    description: 'Optional grep pattern to filter changed files (e.g., "\.py$" for Python files only)'
    required: false
    default: ''

outputs:
  changed-components:
    description: 'Space-separated list of changed component paths (e.g., components/training/my_trainer)'
    value: ${{ steps.detect.outputs.changed-components }}
  changed-pipelines:
    description: 'Space-separated list of changed pipeline paths (e.g., pipelines/training/my_pipeline)'
    value: ${{ steps.detect.outputs.changed-pipelines }}
  changed-components-json:
    description: 'JSON array of changed component paths'
    value: ${{ steps.detect.outputs.changed-components-json }}
  changed-pipelines-json:
    description: 'JSON array of changed pipeline paths'
    value: ${{ steps.detect.outputs.changed-pipelines-json }}
  changed-components-count:
    description: 'Number of changed components'
    value: ${{ steps.detect.outputs.changed-components-count }}
  changed-pipelines-count:
    description: 'Number of changed pipelines'
    value: ${{ steps.detect.outputs.changed-pipelines-count }}
  has-changes:
    description: 'Whether any components, pipelines, or file types have changed (true/false)'
    value: ${{ steps.detect.outputs.has-changes }}
  has-changed-components:
    description: 'Whether any components have changed (true/false)'
    value: ${{ steps.detect.outputs.has-changed-components }}
  has-changed-pipelines:
    description: 'Whether any pipelines have changed (true/false)'
    value: ${{ steps.detect.outputs.has-changed-pipelines }}
  changed-python-files:
    description: 'Space-separated list of changed Python files (.py)'
    value: ${{ steps.detect.outputs.changed-python-files }}
  changed-python-files-json:
    description: 'JSON array of changed Python files'
    value: ${{ steps.detect.outputs.changed-python-files-json }}
  changed-python-files-count:
    description: 'Number of changed Python files'
    value: ${{ steps.detect.outputs.changed-python-files-count }}
  has-changed-python-files:
    description: 'Whether any Python files have changed (true/false)'
    value: ${{ steps.detect.outputs.has-changed-python-files }}
  changed-markdown-files:
    description: 'Space-separated list of changed Markdown files (.md)'
    value: ${{ steps.detect.outputs.changed-markdown-files }}
  changed-markdown-files-json:
    description: 'JSON array of changed Markdown files'
    value: ${{ steps.detect.outputs.changed-markdown-files-json }}
  changed-markdown-files-count:
    description: 'Number of changed Markdown files'
    value: ${{ steps.detect.outputs.changed-markdown-files-count }}
  has-changed-markdown-files:
    description: 'Whether any Markdown files have changed (true/false)'
    value: ${{ steps.detect.outputs.has-changed-markdown-files }}
  changed-yaml-files:
    description: 'Space-separated list of changed YAML files (.yaml, .yml)'
    value: ${{ steps.detect.outputs.changed-yaml-files }}
  changed-yaml-files-json:
    description: 'JSON array of changed YAML files'
    value: ${{ steps.detect.outputs.changed-yaml-files-json }}
  changed-yaml-files-count:
    description: 'Number of changed YAML files'
    value: ${{ steps.detect.outputs.changed-yaml-files-count }}
  has-changed-yaml-files:
    description: 'Whether any YAML files have changed (true/false)'
    value: ${{ steps.detect.outputs.has-changed-yaml-files }}
  all-changed-files:
    description: 'All changed files'
    value: ${{ steps.detect.outputs.all-changed-files }}
  filtered-changed-files:
    description: 'Changed files matching any filter pattern'
    value: ${{ steps.detect.outputs.filtered-changed-files }}

runs:
  using: 'composite'
  steps:
    - name: Detect changed assets
      id: detect
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        .github/scripts/detect-changed-assets/detect.sh \
          "${{ inputs.base-ref }}" \
          "${{ inputs.head-ref }}" \
          "${{ inputs.include-third-party }}" \
          "${{ inputs.filter }}"

branding:
  icon: 'file-text'
  color: 'blue'

