name: Get Changed Files
description: Get changed files by extension
inputs:
  patterns:
    description: 'File patterns to match (e.g., "*.py" or "*.md")'
    required: true
outputs:
  files:
    description: 'Space-separated list of changed files'
    value: ${{ steps.get-files.outputs.files }}
  any_changed:
    description: 'Whether any files changed'
    value: ${{ steps.get-files.outputs.any_changed }}
runs:
  using: composite
  steps:
    - name: Get changed files
      id: get-files
      shell: bash
      run: |
        PATTERNS="${{ inputs.patterns }}"
        
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          BASE="origin/${{ github.base_ref }}"
          FILES=$(git diff --name-only --diff-filter=ACMRT "${BASE}...HEAD" -- $PATTERNS | xargs)
        else
          BEFORE="${{ github.event.before }}"
          if [ "$BEFORE" = "0000000000000000000000000000000000000000" ]; then
            # First push or force push - check all files
            FILES=$(git ls-files -- $PATTERNS | xargs)
          else
            FILES=$(git diff --name-only --diff-filter=ACMRT "$BEFORE" "${{ github.sha }}" -- $PATTERNS | xargs)
          fi
        fi
        
        echo "files=$FILES" >> $GITHUB_OUTPUT
        [ -n "$FILES" ] && echo "any_changed=true" >> $GITHUB_OUTPUT || echo "any_changed=false" >> $GITHUB_OUTPUT

